export enum QuerySWRKeys {
  PAST_EVENTS = 'PAST_EVENTS',
  UPCOMING_EVENTS = 'UPCOMING_EVENTS',
  PAST_EVENTS_BY_COMMITTEE = 'PAST_EVENTS_BY_COMMITTEE',
  UPCOMING_EVENTS_BY_COMMITTEE = 'UPCOMING_EVENTS_BY_COMMITTEE',
}
